### ISSUE TITLE
ClickToPlugin 2.5.1 causes display anomaly on Rally

### ISSUE THREAD

**Issue by blalor** [hoyois/safariextensions#4]
My software development team uses [Rally](http://rally1.rallydev.com) for managing our workload .  I have `rally1.rallydev.com` in both "Allow plug-ins on these sites" and "Allow plug-ins from these sources".  I get no prompts when "Block plug-ins manually" is checked.  When ClickToPlugin is enabled, and I click on the "+" icon to expand the list of tasks for a user story, the tree doesn't expand; if I wave the mouse cursor over that region of the page, it renders partially.  I have to reload the page in order to get it to display correctly.  If I disable ClickToPlugin via either Safari's extensions preferences or the context menu, the page renders properly.

Here is a screen recording I made with QuicktimePlayer: [Rally and ClickToPlugin, 3.7MB](http://dl.dropbox.com/u/6953511/screenshots/Rally%20and%20ClickToPlugin.m4v)

Other installed and active extensions:
- AdBlock 2.4.48
- YouTube5 2.2.7
- FlickrPlus 0.8.5
- FacebookBlocker 1.2
- autocomplete 1.0
- NoMoreiTunes 2.11
- Ghostery 1.2.0
- 1Password 3.8.5
- Moofmarks 1.5

**Comment by hoyois** [comment]
Do you know if it worked with a previous version of CTP?
To make sure this is a CTP-only issue, try with all other extensions disabled.
I see a "Rally" in the context menu. Where does that come from?

**Comment by blalor** [comment]
The "Rally" entry in the context menu comes from 1Password.  I have just confirmed that the problem exists when CTP is the only active extension.  I've been using CTP for as long as Safari's supported extensions, and Rally for longer and only noticed this problem in the last couple of months.  I think this cropped up around the time that Safari 5.1 came out, but please don't hold me to that!

**Comment by hoyois** [comment]
Ok, so if you do not whitelist anything on this site, and enable manual blocking, are there any dialogs when you load the page and what do they say?

**Comment by blalor** [comment]
I get this dialog with manual blocking enabled:

![screenshot](http://dl.dropbox.com/u/6953511/screenshots/Screen%20shot%202011-09-26%20at%2010.06.38%20AM.png)

However, the window refreshes normally when manual blocking is enabled: the tree expands in the background while the dialog is displayed.

**Comment by hoyois** [comment]
That last statement is surprising. So the problem does not actually appear if you let CTP block that Flash graph?
Either way, I don't think there's anything I can do about this. Whatever is going on, the extension cannot possibly be to blame since this is a page rendering bug. Moreover, the twenty lines of code that are executed when the element is whitelisted are so innocuous that I couldn't even begin to try to work around it…
The problem may already be fixed in the WebKit nightly builds. If not, a bug report should be filed, but for that I would really need to have access to such a page so that I can produce a reduced test case.

**Comment by blalor** [comment]
The problem doesn't show itself _regardless_ of whether I click "Cancel" or "OK".  Once I dismiss the dialog, the page renders correctly.

Thanks for your time, Marc.

**Comment by hoyois** [comment]
Right, nothing should happen while a dialog is being shown (that's because the web content process is mostly single-threaded). But if you click OK, then the Flash object is not loaded, which shows that this Flash object does not control the tree expansion. In fact, if I understand correctly, the rendering bug only happens when Flash is not blocked, so the rendering of Flash is probably related to the rendering quirk in the tree. Why it works with CTP disabled I cannot explain, but it may simply be a timing issue (the Flash object being loaded maybe one millisecond later than normal when whitelisted).
I don't know how important that graph thingy at the top is, but I suggest that you simply not whitelist that object.

**Comment by blalor** [comment]
The rendering bug is independent of whether the Flash graph is blocked.  I still see the problem when the Flash is whitelisted.

**Comment by hoyois** [comment]
I thought the tree expanded fine when you blocked the Flash manually above.

**Comment by blalor** [comment]
On Sep 27, 2011, at 12:03 PM, Marc Hoyois wrote:

> I thought the tree expanded fine when you blocked the Flash manually above.

The tree expands normally whenever manual blocking is enabled, regardless of whether I choose Cancel or OK.  Just having the dialog pop up allows the normal rendering to take place.

**Comment by hoyois** [comment]
Ok so there's one case that you've not mentioned explicitly: what happens if you let CTP block the Flash normally (i.e., not whitelisted and no manual blocking)?

**Comment by blalor** [comment]
The rendering is still messed up, in that case.

**Comment by hoyois** [comment]
I see. That's quite a confusing issue, but like I said, there's little hope of doing anything about it if I cannot access a sample page. Then I could create a minimal extension reproducing the problem, which would either show a possible workaround or show that it cannot be helped.

**Comment by blalor** [comment]
I was looking for a way to get a trial account, but that doesn't seem possible.  Regardless, Rally's made some UI changes in the last few days and the problem seems to have resolved itself.  :-)
